In [1]:
x = [
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
]
# Access of element of 2d rray
op = x[1][1]  


15


In [3]:
##traverse all element
for i in x: #row
    for j in i:  #i th row traversla of jth column
        print(j,end = ' ')
    print()

11 12 13 
14 15 16 
17 18 19 


In [21]:
# Accesss two metrics array
x1 = [
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
]
x2 = [
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
]

# Access of element of 2d rray
result = []

# matric addition
for i in range(len(x1)):
    row = []
    for j in range(len(x1[0])):
        row.append(x1[i][j]+x2[i][j])
    result.append(row)
    
# print Output
for i in result:
    for j in i:
        print(j,end=' ')
    print()

22 24 26 
28 30 32 
34 36 38 


# Using Numpy

In [4]:
import numpy as np
x1 = np.array([
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
])
x2 = np.array([
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
])
print("New Array")
print(x1+x2)

New Array
[[22 24 26]
 [28 30 32]
 [34 36 38]]


In [11]:
import numpy as np
x1 = np.array([
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
], dtype = complex)
print(x1)

[[11.+0.j 12.+0.j 13.+0.j]
 [14.+0.j 15.+0.j 16.+0.j]
 [17.+0.j 18.+0.j 19.+0.j]]


zeor() and once()

In [22]:
y = np.ones((2,4),dtype = np.int32)
print(y)

[[1 1 1 1]
 [1 1 1 1]]


In [26]:
y = np.zeros((2,4))
print(y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
y = np.ones((2,4),dtype = [('m','int'),('n','float')])
print(y)

[[(1, 1.) (1, 1.) (1, 1.) (1, 1.)]
 [(1, 1.) (1, 1.) (1, 1.) (1, 1.)]]


In [32]:
w = np.arange(1,24,2).reshape(3,4)
print(w)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


In [34]:
print("Row 0:",w[0])
print("Row 1:",w[1])
print("Row 1:",w[-1])  #Negative Indexing

Row 0: [1 3 5 7]
Row 1: [ 9 11 13 15]
Row 1: [17 19 21 23]


In [36]:
#slicing Operatr
print(w[1:])

[[ 9 11 13 15]
 [17 19 21 23]]


In [40]:
print(w[:0:-1])  # reverse array

[[17 19 21 23]
 [ 9 11 13 15]]


In [50]:
#Column Access
print("Column - 0",w[:,0])
print("Column - 1",w[:,1])
print("Column - 1",w[:,-1]) # negative Indexing


Column - 0 [ 1  9 17]
Column - 1 [ 3 11 19]
Column - 1 [ 7 15 23]
